# Generated by Django 4.2.5 on 2023-10-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=1000)),
                ('url_title', models.CharField(max_length=200)),
                ('display_order', models.IntegerField()),
            ],
        ),
    ]
