# Generated by Django 4.2.5 on 2023-10-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0004_alter_slider_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='image',
            field=models.ImageField(default='', max_length=500, upload_to='images/sliders', verbose_name='تصویر اسلایدر'),
            preserve_default=False,
        ),
    ]
